# Generated by Django 5.1.7 on 2025-05-05 19:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='numero',
            field=models.CharField(default=uuid.UUID('8e3c9860-5c1e-4bd6-8393-45f2a7f5a594'), max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ci',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
