# Generated by Django 5.1.7 on 2025-05-05 19:38

import banco.models.cuenta
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0003_alter_cuenta_numero_alter_usuario_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='numero',
            field=models.CharField(default=banco.models.cuenta.generar_numero_cuenta, max_length=12, unique=True),
        ),
    ]
