# Generated by Django 5.1.7 on 2025-05-05 20:31

import banco.models.cuenta
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0005_alter_cuenta_numero_alter_cuenta_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='numero',
            field=models.CharField(default=banco.models.cuenta.generar_numero_cuenta, max_length=6, unique=True),
        ),
    ]
