# Generated by Django 5.1.7 on 2025-05-05 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0006_alter_cuenta_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='cuentaOrigen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_origen', to='banco.cuenta'),
        ),
    ]
