# Generated by Django 5.1.7 on 2025-05-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0007_alter_transaccion_cuentaorigen'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='es_principal',
            field=models.BooleanField(default=True),
        ),
    ]
